#!/bin/bash
# Tier 651 — the notes of the tax previews are written for the person who
# reads them
#
# The previews close with notes for the owner and the tax adviser: what the
# figure is made of, what the adviser still has to add. They were written
# while the forms were built and said so: "Tier 506: Steuerrückstellungen …",
# "v1: Berater trägt die Vorauszahlungen via PUT /gewst/settings ein",
# "v2: Korrekturen werden aus Company.settings.kst1Korrekturen[year]
# gelesen", "Rechnungen (status=paid/sent/overdue)", "PRIMARY tax form",
# "Nur enthalten, wenn … ODER `settings.anlageKAP === true`". Seventy-five
# such texts in twenty services — on the screen, in the PDFs and in the
# MANIFEST.md of the package the adviser receives. A tier number, a route, a
# field name and a version of the program tell that reader nothing; a
# sentence about "v2" promises something nobody has decided to build.
#
# One of them said the Hebesatz was "konfigurierbar über
# Company.settings.hebesatz". It was not: no page and no route wrote that
# field, so every trade tax — in GewSt 1A, in Anlage G and in KSt 1 — was
# computed at 400 %, whatever the municipality levies. It is entered in the
# Gewerbesteuer section now. And Anlage N cited § 3 EStG (the list of tax-free
# income) for income from employment, which is § 19; the GewSt note told a
# GmbH to check its credit under § 35 EStG, which a corporation does not have.
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/_lib.sh"
TAG="e2e-385-$(date +%s%N | cut -c1-13)"
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
AS() { # method path [body]
  local resp
  resp=$(curl -sS -w "\n%{http_code}" -X "$1" "$API$2" -H "x-user-id: $U" -H "x-company-id: $C" \
    -H "Content-Type: application/json" ${3:+-d "$3"})
  STATUS=$(echo "$resp" | tail -n1); BODY=$(echo "$resp" | sed '$d')
}
YEAR=$(TZ=Europe/Berlin date +%Y); TODAY=$(TZ=Europe/Berlin date +%F)

# What the reader of a tax form cannot use: the number of a development step,
# a field of the data model, a route of the API, a version of the program, a
# status code, a path of the application, a class name.
cat > "$TMP/words.py" <<'PY'
import re
WORDS = re.compile(
    r"\bTier \d+|\btier \d+|Company\.|\bsettings\.\w+|(?:PUT|POST|GET|PATCH|DELETE) /"
    r"|(?<![/\w.-])v[12]\b|\bstatus=|/dashboard/|\w+Service\b|\bPRIMARY\b|Generated by")
PY

note "=== 1. the texts in the source ==="
# Every string literal of the services that build the previews, comments left
# out: a comment is for the developer, a literal reaches the reader.
( cd "$SCRIPT_DIR/.." && python3 - "$TMP" <<'PY' > "$TMP/static.txt"
import glob, io, re, sys
sys.path.insert(0, sys.argv[1])
from words import WORDS
LIT = re.compile(r"'(?:[^'\\]|\\.)*'|\"(?:[^\"\\]|\\.)*\"|`(?:[^`\\]|\\.)*`")
# An import path, the namespace of the ELSTER schema and the name of a logger
# are not texts.
SKIP = re.compile(r"^\s*(?:import |//|\*|/\*)|elsterxml/schema|new Logger\(|\.name\)")
n = files = 0
for p in sorted(glob.glob('src/modules/accounting/*.ts') + glob.glob('src/modules/reports/*.ts')):
    if p.endswith(('.controller.ts', '.dto.ts', '.module.ts', '.spec.ts')): continue
    files += 1
    for i, line in enumerate(io.open(p, encoding='utf-8').read().split('\n'), 1):
        if SKIP.search(line): continue
        for m in LIT.finditer(line):
            # `${…}` is code inside a template, not text
            text = re.sub(r"\$\{[^}]*\}", "", m.group(0))
            if WORDS.search(text):
                n += 1; print('%s:%d: %s' % (p, i, text[:110]))
print('FILES %d HITS %d' % (files, n))
PY
)
FILES=$(sed -n 's/^FILES \([0-9]*\) HITS.*/\1/p' "$TMP/static.txt"); HITS=$(sed -n 's/^FILES [0-9]* HITS //p' "$TMP/static.txt")
[[ "${FILES:-0}" -ge 40 ]] && pass "the services of the previews were read ($FILES files)" || fail "only ${FILES:-0} files read"
if [[ "$HITS" == "0" ]]; then pass "no text of a preview names a tier, a field, a route or a version"
else fail "$HITS texts with developer wording: $(grep -v '^FILES' "$TMP/static.txt" | head -5 | tr '\n' ' ')"; fi

note "=== 2. what the previews answer ==="
read -r U C < <(curl -sS -X POST "$API/api/v1/auth/register" -H "Content-Type: application/json" \
  -d "{\"email\":\"$TAG@example.test\",\"password\":\"Tier651-e2e\",\"companyName\":\"$TAG GmbH\"}" \
  | python3 -c "import sys,json;d=json.load(sys.stdin);print(d['user']['id'], d['user'].get('companyId') or d['company']['id'])" 2>/dev/null)
[[ -n "${C:-}" ]] && pass "fixture: a fresh GmbH" || { fail "register"; summary; exit 1; }
fixture_issuer "$C"
AS POST "/api/v1/customers?companyId=$C" '{"name":"Muster GmbH","type":"business","address":{"street":"Ring 2","postalCode":"80331","city":"München","country":"DE"}}'; K=$(json_field "$BODY" id)
AS POST "/api/v1/invoices?companyId=$C" '{"customerId":"'$K'","issueDate":"'$TODAY'","dueDate":"2099-12-31","items":[{"description":"Leistung","quantity":1,"unit":"Stk","unitPrice":100000,"vatRate":0.19}]}'; I=$(json_field "$BODY" id)
AS PUT "/api/v1/invoices/$I/status?companyId=$C" '{"status":"sent"}'
assert_eq "fixture: an issued invoice, so the forms have figures" "$STATUS" "200"

# Every string the preview answers with — notes, disclaimers, labels.
strings() { python3 - "$TMP" "$1" <<'PY'
import json, sys
sys.path.insert(0, sys.argv[1])
from words import WORDS
def walk(v):
    if isinstance(v, str): yield v
    elif isinstance(v, dict):
        for x in v.values(): yield from walk(x)
    elif isinstance(v, list):
        for x in v: yield from walk(x)
try: d = json.load(open(sys.argv[2]))
except Exception: print('NOJSON'); sys.exit()
texts = [t for t in walk(d) if len(t) > 25]
bad = [t for t in texts if WORDS.search(t)]
print(len(texts), len(bad), (bad[0][:90] if bad else ''))
PY
}
SEEN=0
for f in accounting/euer accounting/anlage-s accounting/anlage-v accounting/anlage-kap accounting/anlage-g \
         accounting/anlage-n accounting/kst1 accounting/anlage-r accounting/anlage-kind accounting/anlage-so \
         accounting/anlage-aus accounting/gewst accounting/bilanz accounting/guv accounting/anhang \
         accounting/ebilanz ustva/ustja; do
  curl -sS "$API/api/v1/$f?year=$YEAR&companyId=$C" -H "x-user-id: $U" -H "x-company-id: $C" -o "$TMP/form.json"
  read -r N BAD FIRST < <(strings "$TMP/form.json")
  if [[ "$N" == "NOJSON" || "${N:-0}" -lt 1 ]]; then fail "$f: no texts in the answer"
  elif [[ "$BAD" == "0" ]]; then pass "$f: $N texts, none with developer wording"; SEEN=$((SEEN + N))
  else fail "$f: $BAD of $N texts with developer wording — $FIRST"; fi
done
[[ "$SEEN" -ge 100 ]] && pass "the previews were read ($SEEN texts)" || fail "only $SEEN texts read"

note "=== 3. the notes say where a figure is entered ==="
AS GET "/api/v1/accounting/gewst?year=$YEAR&companyId=$C"
echo "$BODY" | grep -q "auf der Seite Buchhaltung unter Gewerbesteuer" \
  && pass "GewSt: the advance payments are entered on the accounting page" || fail "GewSt: no place named for the advance payments"
echo "$BODY" | grep -q "änderbar auf der Seite Buchhaltung unter Gewerbesteuer" \
  && pass "GewSt: the note says where the Hebesatz is changed" || fail "GewSt: no place named for the Hebesatz"
echo "$BODY" | grep -q "eine Kapitalgesellschaft rechnet nichts an" \
  && pass "GewSt: no credit under § 35 EStG for a corporation" || fail "GewSt: the note on § 35 EStG"
echo "$BODY" | grep -q "Köln\|Münster" && fail "GewSt: Hebesätze of cities quoted from memory" || pass "GewSt: no city's Hebesatz quoted"
AS GET "/api/v1/accounting/anlage-n?year=$YEAR&companyId=$C"
echo "$BODY" | grep -q "§ 19 EStG" && ! echo "$BODY" | grep -q "§ 3 EStG" \
  && pass "Anlage N: income from employment is § 19 EStG" || fail "Anlage N: the paragraph cited"
AS GET "/api/v1/ustva/ustja?year=$YEAR&companyId=$C"
echo "$BODY" | grep -q "versendet, überfällig oder bezahlt" \
  && pass "UStJA: the invoices counted are named in words" || fail "UStJA: the invoices counted are not named"

note "=== 4. the Hebesatz can be entered ==="
gew() { AS GET "/api/v1/accounting/gewst?year=$YEAR&companyId=$C"; python3 -c "
import sys, json; t = json.load(sys.stdin)['totals']; print(t['$1'])" <<< "$BODY"; }
M=$(gew steuermessbetrag)
assert_eq "fixture: 100 000 € of profit, Messbetrag 3,5 %" "$M" "3500"
assert_eq "nothing entered: 400 %" "$(gew hebesatz)" "400"
assert_eq "nothing entered: trade tax 14 000 €" "$(gew festzusetzendeGewerbesteuer)" "14000"
AS PUT "/api/v1/accounting/gewst/settings?companyId=$C" '{"year":'$YEAR',"q1":1000,"q2":0,"q3":0,"q4":0,"hebesatz":470}'
assert_eq "the Hebesatz is saved with the advance payments" "$STATUS" "200"
assert_eq "GewSt 1A: Kz 7 is 470" "$(gew hebesatz)" "470"
assert_eq "GewSt 1A: 3 500 × 470 % = 16 450 €" "$(gew festzusetzendeGewerbesteuer)" "16450"
assert_eq "GewSt 1A: less 1 000 € paid in advance" "$(gew differenz)" "15450"
AS GET "/api/v1/accounting/kst1?year=$YEAR&companyId=$C"
assert_eq "KSt 1 computes the trade tax at 470 %" "$(python3 -c "import sys,json;print(json.load(sys.stdin)['totals']['gewst'])" <<< "$BODY")" "16450"
AS GET "/api/v1/accounting/anlage-g?year=$YEAR&companyId=$C"
assert_eq "Anlage G uses 470 %" "$(python3 -c "import sys,json;print(json.load(sys.stdin)['totals']['hebesatz'])" <<< "$BODY")" "470"
# A body without it — the section of an older client, or only the advance
# payments — leaves it as it is.
AS PUT "/api/v1/accounting/gewst/settings?companyId=$C" '{"year":'$YEAR',"q1":2000,"q2":0,"q3":0,"q4":0}'
assert_eq "advance payments alone: saved" "$STATUS" "200"
assert_eq "… and the Hebesatz stays" "$(gew hebesatz)" "470"
assert_eq "… with the new advance payment" "$(gew differenz)" "14450"
# § 16 Abs. 4 GewStG: no municipality levies less than 200 %.
for bad in 150 1200 470.5 '"abc"' true; do
  AS PUT "/api/v1/accounting/gewst/settings?companyId=$C" '{"year":'$YEAR',"hebesatz":'$bad'}'
  assert_eq "a Hebesatz of $bad is refused" "$STATUS" "400"
done
assert_eq "a refused Hebesatz changes nothing" "$(gew hebesatz)" "470"

note "=== 5. the same words on the screen ==="
# The sections of the accounting page explain the forms in the same way, in
# three languages.
cat > "$TMP/messages.py" <<'PY'
import io, json, re, sys
RX = re.compile(r"\bTier \d+|Company\.settings|\bsettings\.\w+|(?:PUT|POST|GET|PATCH|DELETE) /"
                r"|(?<![/\w.-])v[12]\b|\bstatus=|Standalone-Trade")
def walk(v, p=''):
    if isinstance(v, str): yield p, v
    elif isinstance(v, dict):
        for k, x in v.items(): yield from walk(x, p + '.' + k if p else k)
for lang in ('de', 'en', 'zh'):
    d = json.load(io.open('%s/messages/%s.json' % (sys.argv[1], lang), encoding='utf-8'))
    all_ = list(walk(d))
    bad = [k for k, v in all_ if RX.search(v)]
    flat = dict(all_)
    print(lang, len(all_), len(bad), bad[0] if bad else '-',
          'ok' if all(flat.get(k) for k in ('gewst.hebesatzLabel', 'gewst.hebesatzHint', 'gewst.hebesatzInvalid')) else 'nolabel',
          'p19' if '§ 19 EStG' in flat.get('anlageN.subtitle', '') else 'p3')
PY
while read -r LANG N BAD FIRST LABEL PARA; do
  [[ "$N" -ge 3000 ]] && pass "$LANG: messages read ($N)" || fail "$LANG: $N messages"
  assert_eq "$LANG: messages with developer wording" "$BAD" "0"
  assert_eq "$LANG: the Hebesatz field has its label, hint and error" "$LABEL" "ok"
  assert_eq "$LANG: Anlage N cites § 19 EStG" "$PARA" "p19"
done < <(python3 "$TMP/messages.py" "$SCRIPT_DIR/../../frontend")
grep -q 'data-testid="gewst-hebesatz"' "$SCRIPT_DIR/../../frontend/src/app/dashboard/accounting/GewstSection.tsx" \
  && pass "the Gewerbesteuer section has the field" || fail "no Hebesatz field in the Gewerbesteuer section"

note "=== 6. the package for the adviser ==="
curl -sS "$API/api/v1/accounting/berater-packager?companyId=$C&year=$YEAR" -H "x-user-id: $U" -H "x-company-id: $C" -o "$TMP/paket.zip"
unzip -p "$TMP/paket.zip" MANIFEST.md > "$TMP/manifest.md" 2>/dev/null
LINES=$(wc -l < "$TMP/manifest.md" | tr -d ' ')
[[ "$LINES" -ge 20 ]] && pass "MANIFEST.md of the package read ($LINES lines)" || fail "MANIFEST.md has $LINES lines"
# (written to a file first: bash 3.2 cannot read a heredoc with backticks
# inside a command substitution)
cat > "$TMP/manifest.py" <<'PY'
import io, re, sys
sys.path.insert(0, sys.argv[1])
from words import WORDS
s = io.open(sys.argv[1] + '/manifest.md', encoding='utf-8').read()
# the file names of the package are in backticks
s = re.sub(r"`[^`]*`", "", s)
bad = [l.strip()[:90] for l in s.split('\n') if WORDS.search(l)]
print(len(bad), bad[0] if bad else '')
PY
BADM=$(python3 "$TMP/manifest.py" "$TMP")
[[ "${BADM%% *}" == "0" ]] && pass "MANIFEST.md: no developer wording" || fail "MANIFEST.md: $BADM"
grep -q "ausdrücklich angefordert" "$TMP/manifest.md" || grep -q "IMMER enthalten" "$TMP/manifest.md" \
  && pass "MANIFEST.md says in words when a form is part of the package" || fail "MANIFEST.md does not say when a form is included"

summary
