#!/usr/bin/env bash
# e2e 44: Role-based access control (RBAC)
#
# Verifies the existing RBAC framework in
# backend/src/auth/roles.guard.ts +
# backend/src/modules/users/users.service.ts
# (UsersService.can() / requireRole()) is
# actually enforced at the controller layer.
#
# Why this test exists:
#   The RBAC framework has been in place
#   since before Tier 13 (see the
#   PERMISSIONS table in users.service.ts:
#     viewer: read-only
#     accountant: read + CRUD on business data
#     admin: full + user management
#   ). But until Tier 13 there was no
#   automated test that an actual viewer
#   was REJECTED when they tried to do
#   admin-only actions. The tests below
#   verify that the inline UsersService.
#   requireRole() calls in users.controller.ts
#   (and the @Auth() + @Require() decorator
#   pattern used by other controllers) do
#   what they claim.
#
# Coverage:
#   1. Admin (role=admin) can read users  → 200
#   2. Admin can change a user's role     → 200
#   3. Admin can deactivate a user        → 200
#   4. Admin can create invitations       → 201
#   5. Accountant is rejected from        → 403
#      user-management actions
#   6. Accountant IS allowed to read      → 200
#      business data (sanity — proves the
#      check is per-action)
#   7. Viewer is rejected from             → 403
#      user-management actions
#   8. Viewer IS allowed to read           → 200
#      business data (sanity)
#
# Permission matrix (see users.service.ts):
#   users.read         → admin only
#   users.invite       → admin only
#   users.changeRole   → admin only
#   users.deactivate   → admin only
#   invoice.read       → viewer+
#   invoice.create     → accountant+
# So the test asserts that viewers/
# accountants are 403 on /users/* (which
# is correct per the design) and 200
# on /invoices (which is also correct).
#
# Setup: we INSERT non-admin users directly
# via psql. We can't go through the /invitations
# flow because the controller deliberately
# doesn't return the raw invitation token
# (it's only sent via email). Bypassing the
# flow is safe because the test only needs
# the user's id + role — the auth path
# doesn't care HOW the user was created,
# only that they exist with the right role.

set -uo pipefail
HOST="${HOST:-http://localhost:3001}"
PASS=0
FAIL=0
COMPANY_ID="ad257ec3-d319-479b-b870-3fe76e8f3111"

assert_eq() {
  local label="$1" expected="$2" actual="$3"
  if [[ "$actual" == "$expected" ]]; then
    echo "  PASS: $label"
    PASS=$((PASS+1))
  else
    echo "  FAIL: $label (expected: $expected, got: $actual)"
    FAIL=$((FAIL+1))
  fi
}

# Use the cached admin token from the
# backend e2e suite.
if [[ ! -f /tmp/cashbook-e2e-auth.env ]]; then
  echo "FATAL: /tmp/cashbook-e2e-auth.env not found" >&2
  exit 1
fi
source /tmp/cashbook-e2e-auth.env
if [[ -z "${USER_ID:-}" || -z "${COMPANY_ID:-}" ]]; then
  echo "FATAL: USER_ID or COMPANY_ID missing" >&2
  exit 1
fi

# Generate bcrypt hash for a test password.
# The hash is generated by the SAME bcrypt
# lib the running backend uses, so
# passwordHash comparisons will succeed.
# (Hardcoding a hash from a different
# bcrypt install is a Tier 5 lesson.)
# Tier 335: ${SCRIPT_DIR} not hardcoded
# dev-machine path. CI runner has no
# /Users/shledergmbh/... so the previous
# cd failed silently and PWHASH stayed empty.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PWHASH=$(cd "${SCRIPT_DIR}/../../backend" && node -e "console.log(require('bcrypt').hashSync('Test1234!', 10))")
# Escape $ in the hash for shell safety
PWHASH_ESC=$(printf '%s' "$PWHASH" | sed "s/\\$/\\\\\\$/g")
# Generate unique UUIDs so re-runs don't collide
RUN_ID="$(date +%s)-$$"
VIEWER_ID="11111111-1111-1111-1111-${RUN_ID:0:12}"
ACCOUNTANT_ID="22222222-2222-2222-2222-${RUN_ID:0:12}"
VIEWER_EMAIL="rbac-viewer-${RUN_ID}@example.com"
ACCOUNTANT_EMAIL="rbac-acc-${RUN_ID}@example.com"

# Cleanup any prior test users from previous
# runs (idempotent).
docker exec de-invoice-postgres psql -U de_invoice -d de_invoice -c \
  "DELETE FROM \"User\" WHERE email IN ('$VIEWER_EMAIL', '$ACCOUNTANT_EMAIL');" >/dev/null 2>&1

echo "=== Setup: insert viewer + accountant ==="
# Use a Python heredoc to insert the users
# (Python doesn't expand $ in the bcrypt
# hash, so the passwordHash survives
# intact through the shell).
export COMPANY_ID VIEWER_ID ACCOUNTANT_ID VIEWER_EMAIL ACCOUNTANT_EMAIL PWHASH
docker exec -i de-invoice-postgres psql -U de_invoice -d de_invoice <<SQL
INSERT INTO "User" (id, "companyId", email, "passwordHash", role, status, "createdAt")
VALUES
  ('${VIEWER_ID}', '${COMPANY_ID}', '${VIEWER_EMAIL}', '${PWHASH_ESC}', 'viewer', 'active', now()),
  ('${ACCOUNTANT_ID}', '${COMPANY_ID}', '${ACCOUNTANT_EMAIL}', '${PWHASH_ESC}', 'accountant', 'active', now());
-- Also insert UserCompany grant rows (the
-- HeaderAuthGuard checks this many-to-many table
-- to verify the user has access to the company).
-- Note: UserCompany has no `id` column — PK is
-- (userId, companyId).
INSERT INTO "UserCompany" ("userId", "companyId", role, "grantedAt")
VALUES
  ('${VIEWER_ID}', '${COMPANY_ID}', 'viewer', now()),
  ('${ACCOUNTANT_ID}', '${COMPANY_ID}', 'accountant', now())
ON CONFLICT ("userId", "companyId") DO NOTHING;
SQL

# Verify the inserts
DB_CHECK=$(docker exec de-invoice-postgres psql -U de_invoice -d de_invoice -tA -c \
  "SELECT role FROM \"User\" WHERE id IN ('$VIEWER_ID', '$ACCOUNTANT_ID') ORDER BY role;" 2>&1 | tr -d ' ' | tr '\n' ',' | head -1)
assert_eq "viewer + accountant rows inserted" "accountant,viewer," "$DB_CHECK"

# Target for the role/status change tests
# (use the viewer itself — we're not
# actually changing the admin's role, we
# just need a real target id to PUT to).
TARGET_ID="$VIEWER_ID"

echo
echo "=== Admin tests (role=admin, sanity) ==="

# 1. Admin reads users → 200
ADMIN_READ=$(curl -sS -o /dev/null -w "%{http_code}" \
  -H "x-user-id: $USER_ID" -H "x-company-id: $COMPANY_ID" \
  "$HOST/api/v1/users?companyId=$COMPANY_ID")
assert_eq "admin GET /users → 200" "200" "$ADMIN_READ"

# 2. Admin can change a user's role
ADMIN_CHANGE=$(curl -sS -o /dev/null -w "%{http_code}" -X PATCH \
  -H "Content-Type: application/json" \
  -H "x-user-id: $USER_ID" -H "x-company-id: $COMPANY_ID" \
  -d '{"role":"viewer"}' \
  "$HOST/api/v1/users/$TARGET_ID/role?companyId=$COMPANY_ID")
assert_eq "admin PATCH /users/:id/role → 200" "200" "$ADMIN_CHANGE"

# 3. Admin can deactivate (and reactivate) a user
ADMIN_DEACT=$(curl -sS -o /dev/null -w "%{http_code}" -X PATCH \
  -H "Content-Type: application/json" \
  -H "x-user-id: $USER_ID" -H "x-company-id: $COMPANY_ID" \
  -d '{"status":"inactive"}' \
  "$HOST/api/v1/users/$TARGET_ID/status?companyId=$COMPANY_ID")
assert_eq "admin PATCH /users/:id/status inactive → 200" "200" "$ADMIN_DEACT"
# Reactivate so subsequent tests still work
curl -sS -o /dev/null -X PATCH \
  -H "Content-Type: application/json" \
  -H "x-user-id: $USER_ID" -H "x-company-id: $COMPANY_ID" \
  -d '{"status":"active"}' \
  "$HOST/api/v1/users/$TARGET_ID/status?companyId=$COMPANY_ID"

# 4. Admin can create invitations.
# (Throttler is 10/hr/IP — if the e2e suite
# already used up the budget, accept 429
# gracefully. The test still proves the
# viewer/accountant cases below because
# their throttled response is ALSO non-2xx,
# so we can't distinguish "denied by role"
# from "denied by throttler" for the denied
# cases. The 3 viewer/accountant role-change
# / deactivate tests are the authoritative
# proof that role enforcement works.)
ADMIN_INVITE=$(curl -sS -o /dev/null -w "%{http_code}" -X POST \
  -H "Content-Type: application/json" \
  -H "x-user-id: $USER_ID" -H "x-company-id: $COMPANY_ID" \
  -d "{\"email\":\"rbac-admin-inv-${RUN_ID}@example.com\",\"role\":\"viewer\"}" \
  "$HOST/api/v1/users/invitations?companyId=$COMPANY_ID")
if [[ "$ADMIN_INVITE" == "201" || "$ADMIN_INVITE" == "429" ]]; then
  echo "  PASS: admin POST /users/invitations → $ADMIN_INVITE (201 = success, 429 = throttled, both prove the endpoint is reachable)"
  PASS=$((PASS+1))
else
  echo "  FAIL: admin POST /users/invitations → expected 201/429, got $ADMIN_INVITE"
  FAIL=$((FAIL+1))
fi

echo
echo "=== Viewer tests (role=viewer) ==="

# 5. Viewer reads users → 403 (users.read is admin-only)
V_READ=$(curl -sS -o /dev/null -w "%{http_code}" \
  -H "x-user-id: $VIEWER_ID" -H "x-company-id: $COMPANY_ID" \
  "$HOST/api/v1/users?companyId=$COMPANY_ID")
assert_eq "viewer GET /users → 403" "403" "$V_READ"

# 6. Viewer is rejected from changing roles
V_CHANGE=$(curl -sS -o /dev/null -w "%{http_code}" -X PATCH \
  -H "Content-Type: application/json" \
  -H "x-user-id: $VIEWER_ID" -H "x-company-id: $COMPANY_ID" \
  -d '{"role":"admin"}' \
  "$HOST/api/v1/users/$TARGET_ID/role?companyId=$COMPANY_ID")
assert_eq "viewer PATCH /users/:id/role → 403" "403" "$V_CHANGE"

# 7. Viewer is rejected from deactivating users
V_DEACT=$(curl -sS -o /dev/null -w "%{http_code}" -X PATCH \
  -H "Content-Type: application/json" \
  -H "x-user-id: $VIEWER_ID" -H "x-company-id: $COMPANY_ID" \
  -d '{"status":"inactive"}' \
  "$HOST/api/v1/users/$TARGET_ID/status?companyId=$COMPANY_ID")
assert_eq "viewer PATCH /users/:id/status → 403" "403" "$V_DEACT"

# 8. Viewer is rejected from creating invitations
# (Throttler may hit first if prior tests in
# the suite used up the 10/hr budget; we
# accept either 403 — the role check rejecting
# — or 429 — the throttler rejecting — as
# evidence that the request was denied. The
# important assertion is that the request
# did NOT succeed.)
V_INVITE=$(curl -sS -o /dev/null -w "%{http_code}" -X POST \
  -H "Content-Type: application/json" \
  -H "x-user-id: $VIEWER_ID" -H "x-company-id: $COMPANY_ID" \
  -d "{\"email\":\"rbac-v-${RUN_ID}@example.com\",\"role\":\"viewer\"}" \
  "$HOST/api/v1/users/invitations?companyId=$COMPANY_ID")
if [[ "$V_INVITE" == "403" || "$V_INVITE" == "429" ]]; then
  echo "  PASS: viewer POST /users/invitations → denied ($V_INVITE)"
  PASS=$((PASS+1))
else
  echo "  FAIL: viewer POST /users/invitations → expected 403/429, got $V_INVITE"
  FAIL=$((FAIL+1))
fi

# 9. Sanity: viewer IS allowed to read invoices
V_INVOICE=$(curl -sS -o /dev/null -w "%{http_code}" \
  -H "x-user-id: $VIEWER_ID" -H "x-company-id: $COMPANY_ID" \
  "$HOST/api/v1/invoices?companyId=$COMPANY_ID")
assert_eq "viewer GET /invoices → 200 (sanity)" "200" "$V_INVOICE"

echo
echo "=== Accountant tests (role=accountant) ==="

# 10. Accountant reads users → 403 (users.read is admin-only)
A_READ=$(curl -sS -o /dev/null -w "%{http_code}" \
  -H "x-user-id: $ACCOUNTANT_ID" -H "x-company-id: $COMPANY_ID" \
  "$HOST/api/v1/users?companyId=$COMPANY_ID")
assert_eq "accountant GET /users → 403" "403" "$A_READ"

# 11. Accountant is rejected from changing roles
A_CHANGE=$(curl -sS -o /dev/null -w "%{http_code}" -X PATCH \
  -H "Content-Type: application/json" \
  -H "x-user-id: $ACCOUNTANT_ID" -H "x-company-id: $COMPANY_ID" \
  -d '{"role":"admin"}' \
  "$HOST/api/v1/users/$TARGET_ID/role?companyId=$COMPANY_ID")
assert_eq "accountant PATCH /users/:id/role → 403" "403" "$A_CHANGE"

# 12. Accountant is rejected from deactivating users
A_DEACT=$(curl -sS -o /dev/null -w "%{http_code}" -X PATCH \
  -H "Content-Type: application/json" \
  -H "x-user-id: $ACCOUNTANT_ID" -H "x-company-id: $COMPANY_ID" \
  -d '{"status":"inactive"}' \
  "$HOST/api/v1/users/$TARGET_ID/status?companyId=$COMPANY_ID")
assert_eq "accountant PATCH /users/:id/status → 403" "403" "$A_DEACT"

# 13. Accountant is rejected from creating invitations
# (Same 403-or-429 logic as the viewer case.)
A_INVITE=$(curl -sS -o /dev/null -w "%{http_code}" -X POST \
  -H "Content-Type: application/json" \
  -H "x-user-id: $ACCOUNTANT_ID" -H "x-company-id: $COMPANY_ID" \
  -d "{\"email\":\"rbac-a-${RUN_ID}@example.com\",\"role\":\"viewer\"}" \
  "$HOST/api/v1/users/invitations?companyId=$COMPANY_ID")
if [[ "$A_INVITE" == "403" || "$A_INVITE" == "429" ]]; then
  echo "  PASS: accountant POST /users/invitations → denied ($A_INVITE)"
  PASS=$((PASS+1))
else
  echo "  FAIL: accountant POST /users/invitations → expected 403/429, got $A_INVITE"
  FAIL=$((FAIL+1))
fi

# 14. Sanity: accountant IS allowed to read invoices
A_INVOICE=$(curl -sS -o /dev/null -w "%{http_code}" \
  -H "x-user-id: $ACCOUNTANT_ID" -H "x-company-id: $COMPANY_ID" \
  "$HOST/api/v1/invoices?companyId=$COMPANY_ID")
assert_eq "accountant GET /invoices → 200 (sanity)" "200" "$A_INVOICE"

echo
echo "=== Cleanup ==="
docker exec de-invoice-postgres psql -U de_invoice -d de_invoice -c \
  "DELETE FROM \"User\" WHERE id IN ('$VIEWER_ID', '$ACCOUNTANT_ID');" >/dev/null 2>&1
docker exec de-invoice-postgres psql -U de_invoice -d de_invoice -c \
  "DELETE FROM \"UserInvitation\" WHERE \"companyId\"='$COMPANY_ID' AND email LIKE 'rbac-%';" >/dev/null 2>&1

echo
echo "==== $PASS passed, $FAIL failed ===="
exit $FAIL
