/**
 * CAMT.053 SEPA XML bank-to-customer statement parser.
 *
 * CAMT.053 follows the ISO 20022 schema and looks like:
 *
 *   <Document>
 *     <BkToCstmrStmt>
 *       <GrpHdr>
 *         <MsgId>...</MsgId>
 *         <CreDtTm>...</CreDtTm>
 *       </GrpHdr>
 *       <Stmt>
 *         <Acct>
 *           <Id><IBAN>DE89...</IBAN></Id>
 *           <Ownr><Nm>Müller GmbH</Nm></Ownr>
 *         </Acct>
 *         <Bal type="OPBD"><Amt>100.00</Amt><Ccy>EUR</Ccy><Dt>2026-06-01</Dt></Bal>
 *         <Bal type="CLBD"><Amt>120.00</Amt><Ccy>EUR</Ccy><Dt>2026-06-30</Dt></Bal>
 *         <Ntry>
 *           <Amt>120.00</Amt><Ccy>EUR</Ccy><CdtDbtInd>CRDT</CdtDbtInd>
 *           <BookgDt><Dt>2026-06-15</Dt></BookgDt>
 *           <ValDt><Dt>2026-06-15</Dt></ValDt>
 *           <NtryRef>...</NtryRef>
 *           <TxDtls>
 *             <CdtTrxTxInf>  (or DbtTrxTxInf for outgoing)
 *               <PmtId><EndToEndId>NOTPROVIDED</EndToEndId></PmtId>
 *               <RmtInf><Ustrd>Invoice INV-2026-000042</Ustrd></RmtInf>
 *               <Dbtr><Nm>Müller GmbH</Nm></Dbtr>      (for credit, this is debtor)
 *               <DbtrAcct><Id><IBAN>DE...</IBAN></Id></DbtrAcct>
 *               ...
 *             </CdtTrxTxInf>
 *           </TxDtls>
 *         </Ntry>
 *       </Stmt>
 *     </BkToCstmrStmt>
 *   </Document>
 *
 * We use simple string scanning for tags instead of a
 * full XML library — CAMT.053 is well-defined and
 * element ordering is fixed, so a focused parser is
 * cleaner than dragging in `fast-xml-parser` for this.
 */

import type { ParsedStatement, ParsedTransaction } from './parsers'

/** Read the content of an XML element by name.
 *  Returns null if the element is missing. We do a
 *  simple "first matching <Tag>...</Tag>" lookup
 *  rather than parsing the whole tree. This is
 *  brittle for non-conforming input but CAMT.053 is
 *  generated by bank software that's very strict. */
function getTag(xml: string, tag: string): string | null {
  const m = xml.match(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`))
  return m ? m[1].trim() : null
}

function getAllTags(xml: string, tag: string): string[] {
  const out: string[] = []
  const re = new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`, 'g')
  let m: RegExpExecArray | null
  while ((m = re.exec(xml)) !== null) {
    out.push(m[1])
  }
  return out
}

function parseAmount(raw: string | null): number | null {
  if (!raw) return null
  const n = Number(raw.replace(',', '.'))
  return Number.isFinite(n) ? n : null
}

function parseDate(raw: string | null): Date | null {
  if (!raw) return null
  // ISO 8601 YYYY-MM-DD
  const m = raw.match(/^(\d{4})-(\d{2})-(\d{2})/)
  if (!m) return null
  const d = new Date(Date.UTC(+m[1], +m[2] - 1, +m[3]))
  return Number.isFinite(d.getTime()) ? d : null
}

export function parseCamt053(xml: string): ParsedStatement[] {
  // Walk every <Stmt> — a single CAMT file can contain
  // multiple statements (multi-account).
  const stmtBlocks = getAllTags(xml, 'Stmt')
  const statements: ParsedStatement[] = []

  for (const stmt of stmtBlocks) {
    // Account
    const iban = getTag(getTag(stmt, 'Acct') || '', 'IBAN') || undefined

    // Bank name from the group header. If multiple
    // statements in one file, all share the same BkNm.
    // We don't bother with per-statement ownership here.
    // (Owner name is in <Acct><Ownr><Nm> if we ever need it.)
    const bankName = undefined // pulled at the BkToCstmrStmt level if needed

    // Open + close balance. CAMT has multiple <Bal>
    // elements tagged by type — we look for OPBD
    // (OpeningBooked) and CLBD (ClosingBooked). CLBD
    // is the equivalent of MT940's :62F:.
    //
    // We need the type attribute, which is on the
    // OPENING tag of <Bal>, not on the inner content.
    // So we can't use getAllTags('Bal') here — we
    // scan the raw text for the opening tag.
    let openingBalance: number | undefined
    let closingBalance: number | undefined
    let currency = 'EUR'
    const balRe = /<Bal type="([^"]+)">([\s\S]*?)<\/Bal>/g
    let bm: RegExpExecArray | null
    while ((bm = balRe.exec(stmt)) !== null) {
      const type = bm[1]
      const inner = bm[2]
      const amt = parseAmount(getTag(inner, 'Amt'))
      const ccy = getTag(inner, 'Ccy') || 'EUR'
      if (amt !== null) {
        if (type === 'OPBD') openingBalance = amt
        if (type === 'CLBD') closingBalance = amt
        currency = ccy
      }
    }

    // Walk every <Ntry> (entry = one transaction).
    const transactions: ParsedTransaction[] = []
    for (const ntry of getAllTags(stmt, 'Ntry')) {
      const amt = parseAmount(getTag(ntry, 'Amt'))
      if (amt === null) continue
      const ccy = getTag(ntry, 'Ccy') || currency
      const sign = getTag(ntry, 'CdtDbtInd') === 'DBIT' ? -1 : 1
      const valDtRaw = getTag(ntry, 'ValDt')
      const bookDtRaw = getTag(ntry, 'BookgDt')
      const valueDate = parseDate(getTag(valDtRaw || '', 'Dt'))
        || parseDate(getTag(bookDtRaw || '', 'Dt'))
      const entryDate = parseDate(getTag(bookDtRaw || '', 'Dt')) || undefined
      if (!valueDate) continue

      // We only care about one TxDtls block per Ntry —
      // some banks emit multiple but the amounts must
      // add up to the entry amount. Take the first.
      const txDetailsList = getAllTags(ntry, 'TxDtls')
      const tx = txDetailsList[0] || ntry

      // Purpose — RmtInf/Ustrd is the unstructured
      // remittance info. It's the most reliable place
      // to find the invoice number.
      const rmt = getTag(tx, 'RmtInf') || ''
      const purpose = getTag(rmt, 'Ustrd') || getTag(rmt, 'Strd') || undefined

      // Counterparty: for credits the counterparty is
      // the Dbtr (debtor — the one paying us); for
      // debits the counterparty is the Cdtr (creditor —
      // the one we're paying). CAMT separates the
      // sub-tags: CdtTrxTxInf for credits has Dbtr +
      // DbtrAcct; DbtTrxTxInf for debits has Cdtr +
      // CdtrAcct. Pick the one that exists.
      const cdt = getTag(tx, 'CdtTrxTxInf')
      const dbt = getTag(tx, 'DbtTrxTxInf')
      const party = cdt || dbt || ''
      const partyName = getTag(party, 'Nm') || undefined
      const partyAcct = getTag(party, 'Acct') || ''
      const partyIban = getTag(partyAcct, 'IBAN') || undefined

      // End-to-end id
      const pmtId = getTag(tx, 'PmtId') || ''
      const endToEndId = getTag(pmtId, 'EndToEndId') || undefined

      transactions.push({
        valueDate,
        entryDate,
        amount: sign * amt,
        currency: ccy,
        counterpartyName: partyName,
        counterpartyIban: partyIban,
        purpose,
        endToEndId,
      })
    }

    statements.push({
      format: 'camt053',
      accountIban: iban,
      bankName,
      openingBalance,
      closingBalance,
      currency,
      transactions,
    })
  }
  return statements
}

/** Format auto-detection. MT940 starts with `:1:` (header
 *  of an SWIFT message) and has `:20:`. CAMT.053 always
 *  starts with `<?xml` and contains `<Document>`. */
export function detectFormat(text: string): 'mt940' | 'camt053' {
  const trimmed = text.trim()
  if (trimmed.startsWith('<?xml') || trimmed.startsWith('<')) return 'camt053'
  if (trimmed.includes(':20:') || trimmed.includes(':60F:') || trimmed.includes(':25:')) return 'mt940'
  // Fallback to MT940 — error path will be on the parser
  return 'mt940'
}
