#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
# de-invoice — Cloudflare IP list auto-refresh (Tier 19)
#
# Pulls the current CF edge IP list and rewrites
# cloudflare-real-ip.conf so it stays in sync with CF's actual
# edge network. Run weekly via the systemd timer in this dir.
#
# Usage:
#   bash refresh-cloudflare-ips.sh          # dry-run (default)
#   bash refresh-cloudflare-ips.sh --apply  # write file + reload nginx
#
# Why a separate script:
#   CF changed their edge IP list ~10 times between 2014 and
#   2026. Last change was April 2024. Without automation, ops
#   has to notice and update manually — and the first sign of
#   "ops didn't notice" is "rate-limit stopped working for some
#   users" (the new CF edge IPs are NOT in set_real_ip_from,
#   so real_ip_header is ignored for them, and $remote_addr
#   falls back to the CF edge IP).
#
# Safety:
#   - Validates every line is a legal CIDR before writing
#   - Validates new content with nginx -t BEFORE reloading
#   - Never touches the file if validation fails
#   - Logs to /var/log/cloudflare-refresh.log
#   - Writes atomically (write to .tmp, then mv)
# ─────────────────────────────────────────────────────────────────

set -euo pipefail

# ─── Config ───────────────────────────────────────────────
CF_IPV4_URL="https://www.cloudflare.com/ips-v4/"
CF_IPV6_URL="https://www.cloudflare.com/ips-v6/"
OUTPUT_PATH="${OUTPUT_PATH:-/etc/nginx/cloudflare/cloudflare-real-ip.conf}"
LOG_PATH="${LOG_PATH:-/var/log/cloudflare-refresh.log}"
CURL_TIMEOUT="${CURL_TIMEOUT:-30}"

# ─── Logging ──────────────────────────────────────────────
log() {
  local ts
  ts="$(date '+%Y-%m-%dT%H:%M:%S%z')"
  # Log to stderr so it doesn't pollute stdout (which we use
  # to return the IP list from fetch_and_validate). systemd
  # captures both — `journalctl -u cloudflare-refresh` shows
  # everything.
  echo "[$ts] $*" >&2
  echo "[$ts] $*" >> "$LOG_PATH"
}

# ─── CIDR validation ─────────────────────────────────────
# Validates a single CIDR string: "1.2.3.4/20" or "::/32".
# Uses ipcalc-style validation via python (always available
# in nginx containers, common on Linux servers).
validate_cidr() {
  local cidr="$1"
  python3 - "$cidr" <<'PY'
import ipaddress
import sys
try:
  ipaddress.ip_network(sys.argv[1], strict=False)
  sys.exit(0)
except ValueError:
  sys.exit(1)
PY
}

# ─── Fetch + validate ─────────────────────────────────────
fetch_and_validate() {
  local url="$1"
  log "Fetching $url..."

  # curl with timeout. --fail makes curl exit non-zero on HTTP errors
  # (e.g. 404, 5xx). We pipe to a temp file so we can validate before
  # touching the output.
  local tmp
  tmp="$(mktemp)"
  if ! curl -fsSL --max-time "$CURL_TIMEOUT" "$url" -o "$tmp"; then
    log "ERROR: curl failed for $url"
    rm -f "$tmp"
    return 1
  fi

  # Validate every line is a CIDR.
  local bad=0
  local total=0
  while IFS= read -r line; do
    # Skip blank lines (CF's list has none but be defensive)
    [[ -z "$line" ]] && continue
    total=$((total + 1))
    if ! validate_cidr "$line"; then
      log "ERROR: invalid CIDR on line $total: '$line'"
      bad=$((bad + 1))
    fi
  done < "$tmp"

  if [[ $bad -gt 0 ]]; then
    log "ERROR: $bad/$total CIDRs failed validation, aborting"
    rm -f "$tmp"
    return 1
  fi

  log "Validated $total CIDRs from $url"
  cat "$tmp"
  rm -f "$tmp"
}

# ─── Render output ────────────────────────────────────────
render_output() {
  local v4="$1" v6="$2"
  cat <<EOF
# ─────────────────────────────────────────────────────────────────
# de-invoice — Cloudflare real-IP restore (Tier 19)
#
# AUTO-GENERATED by refresh-cloudflare-ips.sh on $(date '+%Y-%m-%d %H:%M:%S %Z')
# Source: https://www.cloudflare.com/ips-v4/ and /ips-v6/
#
# DO NOT EDIT THIS FILE BY HAND — your changes will be
# overwritten on the next refresh. To pin a custom value
# (e.g. for testing), edit the script source instead.
# ─────────────────────────────────────────────────────────────────

# Cloudflare IPv4 edge network
$(echo "$v4" | sed 's/^/set_real_ip_from /; s/$/;/')

# Cloudflare IPv6 edge network
$(echo "$v6" | sed 's/^/set_real_ip_from /; s/$/;/')

real_ip_header CF-Connecting-IP;
real_ip_recursive on;
EOF
}

# ─── Diff check ───────────────────────────────────────────
# Skip the write+reload if the new content matches what's
# already on disk. This avoids pointless nginx reloads (which
# briefly drop in-flight requests on some configs).
diff_check() {
  local new="$1"
  if [[ -f "$OUTPUT_PATH" ]] && diff -q <(echo "$new") "$OUTPUT_PATH" > /dev/null 2>&1; then
    log "No changes — current $OUTPUT_PATH already up to date"
    return 1   # signal "no change"
  fi
  return 0     # signal "has changes"
}

# ─── Main ─────────────────────────────────────────────────
main() {
  local apply=false
  if [[ "${1:-}" == "--apply" ]]; then
    apply=true
  fi

  log "=== refresh-cloudflare-ips.sh $( $apply && echo "APPLY" || echo "DRY-RUN" ) ==="

  local v4 v6
  v4="$(fetch_and_validate "$CF_IPV4_URL")" || { log "Aborted"; exit 1; }
  v6="$(fetch_and_validate "$CF_IPV6_URL")" || { log "Aborted"; exit 1; }

  local new_content
  new_content="$(render_output "$v4" "$v6")"

  if ! diff_check "$new_content"; then
    log "Done (no changes)"
    exit 0
  fi

  if [[ "$apply" != true ]]; then
    log "DRY-RUN: would write to $OUTPUT_PATH"
    log "--- preview ---"
    echo "$new_content" | head -20
    log "--- end preview ---"
    exit 0
  fi

  # Atomic write: write to tmp, validate, then mv.
  local tmp
  tmp="$(mktemp)"
  echo "$new_content" > "$tmp"

  # nginx -t validates ALL configs (including main nginx.conf which
  # include()s this one). If the new content breaks nginx, this
  # fails and we don't replace the live file.
  if ! sudo nginx -t 2>>"$LOG_PATH"; then
    log "ERROR: nginx -t failed — new config NOT applied"
    log "       tmp file preserved at $tmp for inspection"
    exit 1
  fi

  # mv is atomic on the same filesystem — readers never see
  # a partially-written file.
  sudo install -m 0644 -o root -g root "$tmp" "$OUTPUT_PATH"
  rm -f "$tmp"
  log "Wrote new $OUTPUT_PATH"

  # Reload nginx (graceful — finishes in-flight requests).
  if sudo nginx -s reload 2>>"$LOG_PATH"; then
    log "nginx reloaded successfully"
  else
    log "ERROR: nginx reload failed"
    exit 1
  fi

  log "Done"
}

main "$@"